# Generated by Django 3.2.9 on 2021-11-15 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='box',
            table='boxes',
        ),
    ]
