# Generated by Django 3.2.9 on 2021-11-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0003_boxlimits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxlimits',
            name='A1',
            field=models.FloatField(default=100.0),
        ),
        migrations.AlterField(
            model_name='boxlimits',
            name='L1',
            field=models.FloatField(default=100.0),
        ),
        migrations.AlterField(
            model_name='boxlimits',
            name='L2',
            field=models.FloatField(default=50.0),
        ),
        migrations.AlterField(
            model_name='boxlimits',
            name='V1',
            field=models.FloatField(default=1000.0),
        ),
    ]
